name: Deploy Spring Boot microservice to ECS Fargate

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Remote Hi
        run: echo "Hi from remote"